KEY_WORDS = 0
ANTI_KEY_WORDS = 1
DIFFERENTIATE_KEY_WORDS = 2

#################################################################################################################
###################################################### Management ###############################################
#################################################################################################################

# TODO: defining the keywords in proper way (iterative steps: generating, and see result, if mssing, then add keywords/anti_keywords)
PSY_CALCULUS_KEY_WORDS = ['微積分']
PSY_CALCULUS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_MATH_KEY_WORDS = ['線性代數', '離散', '微分', '機率', '數學']
PSY_MATH_ANTI_KEY_WORDS = ['asdgladfj;l', '通識']
PSY_ECONOMICS_KEY_WORDS = ['經濟學']
PSY_ECONOMICS_ANTI_KEY_WORDS = ['asdgladfj;l', '計量']
PSY_ECONOMETRICS_KEY_WORDS = ['計量經濟']
PSY_ECONOMETRICS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BUSINESS_KEY_WORDS = ['企業', '商事', '商管']
PSY_BUSINESS_ANTI_KEY_WORDS = ['asdgladfj;l', '資料']
PSY_MANAGEMENT_KEY_WORDS = ['管理學', '組織', '管理']
PSY_MANAGEMENT_ANTI_KEY_WORDS = ['asdgladfj;l', '資料', '數學', '實習']
PSY_ACCOUNTING_KEY_WORDS = ['會計', '審計']
PSY_ACCOUNTING_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_STATISTICS_KEY_WORDS = ['統計']
PSY_STATISTICS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_FINANCE_KEY_WORDS = ['金融', '投資', '貨幣',
                         '資本市場', '財務', '期貨', '選擇權', '債券']
PSY_FINANCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_MARKETING_KEY_WORDS = ['行銷']
PSY_MARKETING_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_OP_RESEARCH_KEY_WORDS = ['作業研究']
PSY_OP_RESEARCH_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_EP_RESEARCH_KEY_WORDS = ['觀察研究', '市場分析', '市場研究', '討論']
PSY_EP_RESEARCH_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_PROGRAMMING_KEY_WORDS = ['程式']
PSY_PROGRAMMING_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_DATA_SCIENCE_KEY_WORDS = ['資料']
PSY_DATA_SCIENCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BACHELOR_THESIS_KEY_WORDS = ['專題', '論文']
PSY_BACHELOR_THESIS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_PSYCHOLOGY_KEY_WORDS = ['心理']
PSY_PSYCHOLOGY_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_COGNITIVE_SCIENCE_KEY_WORDS = ['認知']
PSY_COGNITIVE_SCIENCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BEHAVIOR_KEY_WORDS = ['行為']
PSY_BEHAVIOR_ANTI_KEY_WORDS = ['asdgladfj;l']
USELESS_COURSES_KEY_WORDS = ['asdgladfj;l']
USELESS_COURSES_ANTI_KEY_WORDS = ['asdgladfj;l']

#################################################################################################################
########################################## Management English ###################################################
#################################################################################################################

# TODO: defining the keywords in proper way (iterative steps: generating, and see result, if mssing, then add keywords/anti_keywords)
PSY_CALCULUS_KEY_WORDS_EN = ['微積分']
PSY_CALCULUS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MATH_KEY_WORDS_EN = ['linear algebra']
PSY_MATH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_ECONOMICS_KEY_WORDS_EN = ['economic']
PSY_ECONOMICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_ECONOMETRICS_KEY_WORDS_EN = ['econometric']
PSY_ECONOMETRICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BUSINESS_KEY_WORDS_EN = ['business']
PSY_BUSINESS_ANTI_KEY_WORDS_EN = ['asdgladfj;l', '資料']
PSY_MANAGEMENT_KEY_WORDS_EN = ['管理學', '組織']
PSY_MANAGEMENT_ANTI_KEY_WORDS_EN = ['asdgladfj;l', '資料']
PSY_ACCOUNTING_KEY_WORDS_EN = ['會計']
PSY_ACCOUNTING_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_STATISTICS_KEY_WORDS_EN = ['統計']
PSY_STATISTICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_FINANCE_KEY_WORDS_EN = ['金融']
PSY_FINANCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MARKETING_KEY_WORDS_EN = ['行銷']
PSY_MARKETING_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_OP_RESEARCH_KEY_WORDS_EN = ['作業研究']
PSY_OP_RESEARCH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_EP_RESEARCH_KEY_WORDS_EN = ['觀察研究']
PSY_EP_RESEARCH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_PROGRAMMING_KEY_WORDS_EN = ['程式']
PSY_PROGRAMMING_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_DATA_SCIENCE_KEY_WORDS_EN = ['資料']
PSY_DATA_SCIENCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BACHELOR_THESIS_KEY_WORDS_EN = ['專題', '論文']
PSY_BACHELOR_THESIS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_PSYCHOLOGY_KEY_WORDS_EN = ['psycho']
PSY_PSYCHOLOGY_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_COGNITIVE_SCIENCE_KEY_WORDS_EN = ['cognit']
PSY_COGNITIVE_SCIENCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BEHAVIOR_KEY_WORDS_EN = ['behavio']
PSY_BEHAVIOR_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
USELESS_COURSES_KEY_WORDS_EN = ['asdgladfj;l']
USELESS_COURSES_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
