KEY_WORDS = 0
ANTI_KEY_WORDS = 1
DIFFERENTIATE_KEY_WORDS = 2

#################################################################################################################
###################################################### Management ###############################################
#################################################################################################################

# TODO: defining the keywords in proper way (iterative steps: generating, and see result, if mssing, then add keywords/anti_keywords)
PSY_CALCULUS_KEY_WORDS = ['微積分']
PSY_CALCULUS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_MATH_KEY_WORDS = ['離散', '微分', '數學']
PSY_MATH_ANTI_KEY_WORDS = ['asdgladfj;l', '通識', '過去', '未來']
PSY_MATH_LIN_KEY_WORDS = ['線性代數']
PSY_MATH_LIN_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_MATH_PROB_KEY_WORDS = ['機率', '隨機']
PSY_MATH_PROB_ANTI_KEY_WORDS = ['asdgladfj;l', '學習', '管理']
PSY_ECONOMICS_KEY_WORDS = ['經濟學']
PSY_ECONOMICS_ANTI_KEY_WORDS = ['asdgladfj;l', '計量']
PSY_ECONOMETRICS_KEY_WORDS = ['計量經濟']
PSY_ECONOMETRICS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BUSINESS_KEY_WORDS = ['企業', '商事', '商管']
PSY_BUSINESS_ANTI_KEY_WORDS = ['asdgladfj;l', '資料']
PSY_MANAGEMENT_KEY_WORDS = ['管理學', '組織', '管理']
PSY_MANAGEMENT_ANTI_KEY_WORDS = ['asdgladfj;l', '資料', '數學', '實習']
PSY_STATISTICS_KEY_WORDS = ['統計']
PSY_STATISTICS_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_FINANCE_KEY_WORDS = ['金融', '投資', '貨幣',
                         '資本市場', '財務', '期貨', '選擇權', '債券']
PSY_FINANCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_MARKETING_KEY_WORDS = ['行銷']
PSY_MARKETING_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_OP_RESEARCH_KEY_WORDS = ['作業研究']
PSY_OP_RESEARCH_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_EP_RESEARCH_KEY_WORDS = ['觀察研究', '市場分析', '市場研究', '討論']
PSY_EP_RESEARCH_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_PROGRAMMING_KEY_WORDS = ['程式']
PSY_PROGRAMMING_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_DATA_SCIENCE_KEY_WORDS = ['資料']
PSY_DATA_SCIENCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BACHELOR_THESIS_KEY_WORDS = ['專題', '論文', '研究']
PSY_BACHELOR_THESIS_ANTI_KEY_WORDS = ['asdgladfj;l', '作業', '觀察']
PSY_PSYCHOLOGY_KEY_WORDS = ['心理']
PSY_PSYCHOLOGY_ANTI_KEY_WORDS = ['asdgladfj;l', '實驗']
PSY_PSYCHOLOGY_EXP_KEY_WORDS = ['心理']
PSY_PSYCHOLOGY_EXP_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_COGNITIVE_SCIENCE_KEY_WORDS = ['認知']
PSY_COGNITIVE_SCIENCE_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_BEHAVIOR_KEY_WORDS = ['行為']
PSY_BEHAVIOR_ANTI_KEY_WORDS = ['asdgladfj;l']
PSY_NEURO_SCIENCE_KEY_WORDS = ['神經科學']
PSY_NEURO_SCIENCE_ANTI_KEY_WORDS = ['asdgladfj;l']
USELESS_COURSES_KEY_WORDS = ['asdgladfj;l']
USELESS_COURSES_ANTI_KEY_WORDS = ['asdgladfj;l']

#################################################################################################################
########################################## Management English ###################################################
#################################################################################################################

# TODO: defining the keywords in proper way (iterative steps: generating, and see result, if mssing, then add keywords/anti_keywords)
PSY_CALCULUS_KEY_WORDS_EN = ['calculu']
PSY_CALCULUS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MATH_KEY_WORDS_EN = ['mathematic']
PSY_MATH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MATH_LIN_KEY_WORDS_EN = ['linear algebra']
PSY_MATH_LIN_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MATH_PROB_KEY_WORDS_EN = ['probabi', '隨機']
PSY_MATH_PROB_ANTI_KEY_WORDS_EN = ['asdgladfj;l', '學習', '管理']
PSY_ECONOMICS_KEY_WORDS_EN = ['economic']
PSY_ECONOMICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_ECONOMETRICS_KEY_WORDS_EN = ['econometric']
PSY_ECONOMETRICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BUSINESS_KEY_WORDS_EN = ['business']
PSY_BUSINESS_ANTI_KEY_WORDS_EN = ['asdgladfj;l', '資料']
PSY_MANAGEMENT_KEY_WORDS_EN = ['management', 'organiz']
PSY_MANAGEMENT_ANTI_KEY_WORDS_EN = ['asdgladfj;l', '資料']
PSY_STATISTICS_KEY_WORDS_EN = ['statisti']
PSY_STATISTICS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_FINANCE_KEY_WORDS_EN = ['finan']
PSY_FINANCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_MARKETING_KEY_WORDS_EN = ['marketing']
PSY_MARKETING_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_OP_RESEARCH_KEY_WORDS_EN = ['operational resear']
PSY_OP_RESEARCH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_EP_RESEARCH_KEY_WORDS_EN = ['empirical resear']
PSY_EP_RESEARCH_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_PROGRAMMING_KEY_WORDS_EN = ['programming']
PSY_PROGRAMMING_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_DATA_SCIENCE_KEY_WORDS_EN = ['datda']
PSY_DATA_SCIENCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BACHELOR_THESIS_KEY_WORDS_EN = ['project', '論文']
PSY_BACHELOR_THESIS_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_PSYCHOLOGY_KEY_WORDS_EN = ['psycho']
PSY_PSYCHOLOGY_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_PSYCHOLOGY_EXP_KEY_WORDS_EN = ['psycho']
PSY_PSYCHOLOGY_EXP_ANTI_KEY_WORDS_EN = ['asdgladfj;l', 'lab', 'experi']
PSY_COGNITIVE_SCIENCE_KEY_WORDS_EN = ['cognit']
PSY_COGNITIVE_SCIENCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_BEHAVIOR_KEY_WORDS_EN = ['behavio']
PSY_BEHAVIOR_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
PSY_NEURO_SCIENCE_KEY_WORDS_EN = ['cogniti']
PSY_NEURO_SCIENCE_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
USELESS_COURSES_KEY_WORDS_EN = ['asdgladfj;l']
USELESS_COURSES_ANTI_KEY_WORDS_EN = ['asdgladfj;l']
