ee_course_db = [
    {"all_course_chinese": "微積分(一)",
     "all_course_english": "Calculus (1)", "category": "ee"},
    {"all_course_chinese": "微積分(二)",
     "all_course_english": "Calculus (2)", "category": "ee"},
    {"all_course_chinese": "線性代數",
        "all_course_english": "Linear algebra", "category": "ee"},
    {"all_course_chinese": "微分方程",
        "all_course_english": "Differential equation", "category": "ee"},
    {"all_course_chinese": "離散數學",
        "all_course_english": "Discrete mathematics", "category": "ee"},
    {"all_course_chinese": "機率與統計",
        "all_course_english": "Probability and Statistics", "category": "ee"},
    {"all_course_chinese": "數值分析",
        "all_course_english": "Numerical Analysis", "category": "ee"},
    {"all_course_chinese": "複變函數",
        "all_course_english": "Complex function", "category": "ee"},
    {"all_course_chinese": "普通物理學(一)",
     "all_course_english": "Physics (1)", "category": "ee"},
    {"all_course_chinese": "普通物理學(二)",
     "all_course_english": "Physics (2)", "category": "ee"},
    {"all_course_chinese": "普通物理學實驗(一)",
     "all_course_english": "Physics Experiment (1)", "category": "ee"},
    {"all_course_chinese": "普通物理學實驗(二)",
     "all_course_english": "Physics Experiment (2)", "category": "ee"},
    {"all_course_chinese": "近代物理",
        "all_course_english": "Modern physics", "category": "ee"},
    {"all_course_chinese": "C++程式設計",
        "all_course_english": "Programming C++", "category": "ee"},
    {"all_course_chinese": "計算機概論",
        "all_course_english": "Introduction to Computer", "category": "ee"},
    {"all_course_chinese": "計算機組織",
        "all_course_english": "Computer organization", "category": "ee"},
    {"all_course_chinese": "計算機結構",
        "all_course_english": "Computer structure", "category": "ee"},
    {"all_course_chinese": "軟體工程",
        "all_course_english": "Software engineering", "category": "ee"},
    {"all_course_chinese": "資料庫", "all_course_english": "Database", "category": "ee"},
    {"all_course_chinese": "嵌入式程式設計",
        "all_course_english": "Embedded programming", "category": "ee"},
    {"all_course_chinese": "作業系統",
        "all_course_english": "Operating system", "category": "ee"},
    {"all_course_chinese": "資料結構",
        "all_course_english": "Data structure", "category": "ee"},
    {"all_course_chinese": "演算法", "all_course_english": "Algorithm", "category": "ee"},
    {"all_course_chinese": "物件導向程式設計",
        "all_course_english": "Object-oriented programming", "category": "ee"},
    {"all_course_chinese": "自動控制(一)",
     "all_course_english": "Automatic control (1)", "category": "ee"},
    {"all_course_chinese": "自動控制(二)",
     "all_course_english": "Automatic control (2)", "category": "ee"},
    {"all_course_chinese": "智慧型控制",
        "all_course_english": "Smart control", "category": "ee"},
    {"all_course_chinese": "控制系統",
        "all_course_english": "Control System", "category": "ee"},
    {"all_course_chinese": "非線性控制系統",
        "all_course_english": "Non-linear control system", "category": "ee"},
    {"all_course_chinese": "電子實驗(一)",
     "all_course_english": "Electronic Experiment (1)", "category": "ee"},
    {"all_course_chinese": "電子實驗(二)",
     "all_course_english": "Electronic Experiment (2)", "category": "ee"},
    {"all_course_chinese": "電子學(一)",
     "all_course_english": "Electronics (1)", "category": "ee"},
    {"all_course_chinese": "電子學(二)",
     "all_course_english": "Electronics (2)", "category": "ee"},
    {"all_course_chinese": "電子學(三)",
     "all_course_english": "Electronics (3)", "category": "ee"},
    {"all_course_chinese": "光電子學(一)",
     "all_course_english": "Optoelectronics (1)", "category": "ee"},
    {"all_course_chinese": "數位邏輯",
        "all_course_english": "Digital logic", "category": "ee"},
    {"all_course_chinese": "積體電路製程技術",
        "all_course_english": "Integrated circuit process technology", "category": "ee"},
    {"all_course_chinese": "積體電路設計",
        "all_course_english": "Integrated circuit design", "category": "ee"},
    {"all_course_chinese": "類比積體電路設計",
        "all_course_english": "Analog integrated circuit design", "category": "ee"},
    {"all_course_chinese": "數位積體電路設計",
        "all_course_english": "Digital integrated circuit design", "category": "ee"},
    {"all_course_chinese": "進階微波被動電路設計與分析",
        "all_course_english": "Advanced microwave passive circuit design and analysis", "category": "ee"},
    {"all_course_chinese": "電子材料",
        "all_course_english": "Electrical Materials", "category": "ee"},
    {"all_course_chinese": "電路學(一)",
     "all_course_english": "Electrical Circuits (1)", "category": "ee"},
    {"all_course_chinese": "電路學(二)",
     "all_course_english": "Electrical Circuits (2)", "category": "ee"},
    {"all_course_chinese": "訊號與系統",
        "all_course_english": "Signal and system", "category": "ee"},
    {"all_course_chinese": "電磁學(一)",
     "all_course_english": "Electromagnetism (1)", "category": "ee"},
    {"all_course_chinese": "電磁學(二)",
     "all_course_english": "Electromagnetism (2)", "category": "ee"},
    {"all_course_chinese": "高頻電路",
        "all_course_english": "High frequency circuit", "category": "ee"},
    {"all_course_chinese": "電力系統規劃和營運",
        "all_course_english": "Power system planning and operation", "category": "ee"},
    {"all_course_chinese": "半導體雷射",
        "all_course_english": "Semiconductor laser", "category": "ee"},
    {"all_course_chinese": "半導體封裝與趨勢發展",
        "all_course_english": "Semiconductor packaging and trend development", "category": "ee"},
    {"all_course_chinese": "半導體製作與量測",
        "all_course_english": "Semiconductor manufacture and measurement", "category": "ee"},
    {"all_course_chinese": "元件設計與模型建立",
        "all_course_english": "Component design and model establishment", "category": "ee"},
    {"all_course_chinese": "半導體元件物理",
        "all_course_english": "Semiconductor component physics", "category": "ee"},
    {"all_course_chinese": "光電元件物理",
        "all_course_english": "Optoelectronics Physics", "category": "ee"},
    {"all_course_chinese": "固態物理",
        "all_course_english": "Solid State Physics", "category": "ee"},
    {"all_course_chinese": "通訊原理(一)",
     "all_course_english": "Communication principle (1)", "category": "ee"},
    {"all_course_chinese": "通訊原理(二)",
     "all_course_english": "Communication Principle (2)", "category": "ee"},
    {"all_course_chinese": "數位通訊",
        "all_course_english": "Digital communication", "category": "ee"},
    {"all_course_chinese": "消息理論",
        "all_course_english": "Message theory", "category": "ee"},
    {"all_course_chinese": "天線原理與設計",
        "all_course_english": "Antenna principle and design", "category": "ee"},
    {"all_course_chinese": "超大型積體電路",
        "all_course_english": "Very large Scale integrated circuit (VLSI)", "category": "ee"},
    {"all_course_chinese": "再生能源導論",
        "all_course_english": "Introduction to Renewable Energy", "category": "ee"},
    {"all_course_chinese": "電力工程概論",
        "all_course_english": "Introduction to Power Engineering", "category": "ee"},
    {"all_course_chinese": "無線網路導論",
        "all_course_english": "Introduction to Wireless Networks", "category": "ee"},
    {"all_course_chinese": "電腦視覺",
        "all_course_english": "Computer vision", "category": "ee"},
    {"all_course_chinese": "影像處理",
        "all_course_english": "Image processing", "category": "ee"},
    {"all_course_chinese": "物聯網技術",
        "all_course_english": "Internet of Things Technology", "category": "ee"},
    {"all_course_chinese": "密碼學與實驗",
        "all_course_english": "Cryptography and experiment", "category": "ee"},
    {"all_course_chinese": "綠能技術與系統",
        "all_course_english": "Green Energy Technology and System", "category": "ee"},
    {"all_course_chinese": "向量分析",
        "all_course_english": "Vector analysis", "category": "ee"},
    {"all_course_chinese": "光電感應技術與應用",
        "all_course_english": "Photoelectric sensing technology and application", "category": "ee"},
    {"all_course_chinese": "應用量子力學(一)",
     "all_course_english": "Applied Quantum Mechanics (1)", "category": "ee"},
    {"all_course_chinese": "再生能源進階實作專題",
        "all_course_english": "Advanced Renewable Energy Implementation Topic", "category": "ee"},
    {"all_course_chinese": "醫學工程導論",
        "all_course_english": "Introduction to Medical Engineering", "category": "ee"},
    {"all_course_chinese": "微波工程導論",
        "all_course_english": "Introduction to Microwave Engineering", "category": "ee"},
    {"all_course_chinese": "靜力學", "all_course_english": "Statics", "category": "ee"},
    {"all_course_chinese": "動力學", "all_course_english": "Dynamics", "category": "ee"},
    {"all_course_chinese": "熱力學",
        "all_course_english": "Thermodynamics", "category": "ee"},
    {"all_course_chinese": "流體力學",
        "all_course_english": "Fluid mechanics", "category": "ee"},
    {"all_course_chinese": "熱傳學", "all_course_english": "Heat transfer", "category": "ee"},
    {"all_course_chinese": "機動學", "all_course_english": "Mobility", "category": "ee"},
    {"all_course_chinese": "通訊網路",
        "all_course_english": "Communication network", "category": "ee"},
    {"all_course_chinese": "電力電子",
        "all_course_english": "Power Electronics", "category": "ee"},
    {"all_course_chinese": "電力系統",
        "all_course_english": "Power Systems", "category": "ee"},
    {"all_course_chinese": "生物影像", "all_course_english": "Bioimaging", "category": "ee"},
    {"all_course_chinese": "電子元件與材料",
        "all_course_english": "Electronic components and materials", "category": "ee"},
    {"all_course_chinese": "聲學", "all_course_english": "Acoustics", "category": "ee"},
    {"all_course_chinese": "射頻工程導論",
        "all_course_english": "Introduction to Radio Frequency", "category": "ee"},
    {"all_course_chinese": "行動通訊",
        "all_course_english": "Mobile communication", "category": "ee"},
    {"all_course_chinese": "資料傳輸",
        "all_course_english": "Data transfer", "category": "ee"},
    {"all_course_chinese": "編譯器原理",
        "all_course_english": "Compiler principle", "category": "ee"},
    {"all_course_chinese": "微系統製造",
        "all_course_english": "Microsystem manufacturing", "category": "ee"},
    {"all_course_chinese": "高頻系統工程",
        "all_course_english": "High frequency system engineering", "category": "ee"},
    {"all_course_chinese": "電動機",
        "all_course_english": "Electric motor", "category": "ee"},
    {"all_course_chinese": "電力電子實驗",
        "all_course_english": "Power Electronics Experiment", "category": "ee"},
    {"all_course_chinese": "電磁波",
        "all_course_english": "Electromagnetic Wave", "category": "ee"},
    {"all_course_chinese": "通道編碼",
        "all_course_english": "Channel Coding", "category": "ee"},
    {"all_course_chinese": "天線理論",
        "all_course_english": "Antenna Theory", "category": "ee"}
]
