import xlsxwriter
from CourseSuggestionAlgorithms import *
from util import *
from keywords import *
from database.ComputerScience.CS_Programs import program_sort_function, column_len_array
from cell_formatter import red_out_failed_subject, red_out_insufficient_credit
import pandas as pd
import sys
import os
env_file_path = os.path.realpath(__file__)
env_file_path = os.path.dirname(env_file_path)


def CS_sorter(program_idx, file_path, abbrev, studentId, student_name, analysis_language):

    basic_classification_en = {
        '基礎資工': [FUNDAMENTAL_COMPUTER_SCIENCE_KEY_WORDS_EN, FUNDAMENTAL_COMPUTER_SCIENCE_ANTI_KEY_WORDS_EN, ['一', '二']],
        '基礎電機電子': [FUNDAMENTAL_ELECTRICAL_ENGINEERING_KEY_WORDS_EN, FUNDAMENTAL_ELECTRICAL_ENGINEERING_ANTI_KEY_WORDS_EN, ['一', '二']],
        '程式設計': [PROGRAMMING_LANGUAGE_KEY_WORDS_EN, PROGRAMMING_LANGUAGE_ANTI_KEY_WORDS_EN, ['一', '二']],
        '電腦結構': [COMPUTER_ARCHITECTURE_KEY_WORDS_EN, COMPUTER_ARCHITECTURE_ANTI_KEY_WORDS_EN, ['一', '二']],
        '軟體工程': [SOFTWARE_ENGINEERING_KEY_WORDS_EN, SOFTWARE_ENGINEERING_ANTI_KEY_WORDS_EN],
        '資料庫': [DATABASE_KEY_WORDS_EN, DATABASE_ANTI_KEY_WORDS_EN],
        '作業系統': [OPERATING_SYSTEM_KEY_WORDS_EN, OPERATING_SYSTEM_ANTI_KEY_WORDS_EN],
        '電腦網絡': [COMPUTER_NETWORK_KEY_WORDS_EN, COMPUTER_NETWORK_ANTI_KEY_WORDS_EN],
        '數理邏輯': [MATHEMATICAL_LOGIC_KEY_WORDS_EN, MATHEMATICAL_LOGIC_PROG_ANTI_KEY_WORDS_EN],
        '圖論': [MATHEMATICAL_GRAPH_THEORY_KEY_WORDS_EN, MATHEMATICAL_GRAPH_THEORY_ANTI_KEY_WORDS_EN],
        '正規方法': [FORMAL_METHOD_KEY_WORDS_EN, FORMAL_METHOD_ANTI_KEY_WORDS_EN],
        '函式程式': [FUNCTIONAL_PROGRAMMING_KEY_WORDS_EN, FUNCTIONAL_PROGRAMMING_ANTI_KEY_WORDS_EN],
        '資料結構演算法': [ALGORITHM_DATASTRUCTURE_KEY_WORDS_EN, ALGORITHM_DATASTRUCTURE_ANTI_KEY_WORDS_EN],
        '理論資工': [THEORY_COMPUTATION_KEY_WORDS_EN, THEORY_COMPUTATION_ANTI_KEY_WORDS_EN],
        '離散': [MATH_DISCRETE_KEY_WORDS_EN, MATH_DISCRETE_ANTI_KEY_WORDS_EN],
        '線性代數': [MATH_LINEAR_ALGEBRA_KEY_WORDS_EN, MATH_LINEAR_ALGEBRA_ANTI_KEY_WORDS_EN],
        '數值分析': [MATH_NUM_METHOD_KEY_WORDS_EN, MATH_NUM_METHOD_ANTI_KEY_WORDS_EN],
        '微積分': [CALCULUS_KEY_WORDS_EN, CALCULUS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '機率': [MATH_PROB_KEY_WORDS_EN, MATH_PROB_ANTI_KEY_WORDS_EN],
        '進階資工': [ADVANCED_COMPUTER_SCIENCE_KEY_WORDS_EN, ADVANCED_COMPUTER_SCIENCE_ANTI_KEY_WORDS_EN],
        '物理化學工程': [CS_PHY_CHEM_NS_ENG_KEY_WORDS_EN, CS_PHY_CHEM_NS_ENG_ANTI_KEY_WORDS_EN],
        '商管經': [CS_BA_BI_ENG_KEY_WORDS_EN, CS_BA_BI_ENG_ANTI_KEY_WORDS_EN],
        '其他': [USELESS_COURSES_KEY_WORDS_EN, USELESS_COURSES_ANTI_KEY_WORDS_EN], }

    basic_classification_zh = {
        '基礎資工': [FUNDAMENTAL_COMPUTER_SCIENCE_KEY_WORDS, FUNDAMENTAL_COMPUTER_SCIENCE_ANTI_KEY_WORDS, ['一', '二']],
        '基礎電機電子': [FUNDAMENTAL_ELECTRICAL_ENGINEERING_KEY_WORDS, FUNDAMENTAL_ELECTRICAL_ENGINEERING_ANTI_KEY_WORDS, ['一', '二']],
        '程式設計': [PROGRAMMING_LANGUAGE_KEY_WORDS, PROGRAMMING_LANGUAGE_ANTI_KEY_WORDS, ['一', '二']],
        '電腦結構': [COMPUTER_ARCHITECTURE_KEY_WORDS, COMPUTER_ARCHITECTURE_ANTI_KEY_WORDS, ['一', '二']],
        '軟體工程': [SOFTWARE_ENGINEERING_KEY_WORDS, SOFTWARE_ENGINEERING_ANTI_KEY_WORDS],
        '資料庫': [DATABASE_KEY_WORDS, DATABASE_ANTI_KEY_WORDS],
        '作業系統': [OPERATING_SYSTEM_KEY_WORDS, OPERATING_SYSTEM_ANTI_KEY_WORDS],
        '電腦網絡': [COMPUTER_NETWORK_KEY_WORDS, COMPUTER_NETWORK_ANTI_KEY_WORDS],
        '數理邏輯': [MATHEMATICAL_LOGIC_KEY_WORDS, MATHEMATICAL_LOGIC_PROG_ANTI_KEY_WORDS],
        '圖論': [MATHEMATICAL_GRAPH_THEORY_KEY_WORDS, MATHEMATICAL_GRAPH_THEORY_ANTI_KEY_WORDS],
        '正規方法': [FORMAL_METHOD_KEY_WORDS, FORMAL_METHOD_ANTI_KEY_WORDS],
        '函式程式': [FUNCTIONAL_PROGRAMMING_KEY_WORDS, FUNCTIONAL_PROGRAMMING_ANTI_KEY_WORDS],
        '資料結構演算法': [ALGORITHM_DATASTRUCTURE_KEY_WORDS, ALGORITHM_DATASTRUCTURE_ANTI_KEY_WORDS],
        '理論資工': [THEORY_COMPUTATION_KEY_WORDS, THEORY_COMPUTATION_ANTI_KEY_WORDS],
        '離散': [MATH_DISCRETE_KEY_WORDS, MATH_DISCRETE_ANTI_KEY_WORDS],
        '線性代數': [MATH_LINEAR_ALGEBRA_KEY_WORDS, MATH_LINEAR_ALGEBRA_ANTI_KEY_WORDS],
        '數值分析': [MATH_NUM_METHOD_KEY_WORDS, MATH_NUM_METHOD_ANTI_KEY_WORDS],
        '微積分': [CALCULUS_KEY_WORDS, CALCULUS_ANTI_KEY_WORDS, ['一', '二']],
        '機率': [MATH_PROB_KEY_WORDS, MATH_PROB_ANTI_KEY_WORDS],
        '進階資工': [ADVANCED_COMPUTER_SCIENCE_KEY_WORDS, ADVANCED_COMPUTER_SCIENCE_ANTI_KEY_WORDS],
        '物理化學工程': [CS_PHY_CHEM_NS_ENG_KEY_WORDS, CS_PHY_CHEM_NS_ENG_ANTI_KEY_WORDS],
        '商管經': [CS_BA_BI_ENG_KEY_WORDS, CS_BA_BI_ENG_ANTI_KEY_WORDS],
        '其他': [USELESS_COURSES_KEY_WORDS, USELESS_COURSES_ANTI_KEY_WORDS], }

    Classifier(program_idx, file_path, abbrev, env_file_path,
               basic_classification_en, basic_classification_zh, column_len_array, program_sort_function, studentId, student_name, analysis_language)
