const { Router } = require('express');

const accountRouter = require('./account');
const admissionsRouter = require('./admissions');
const agentsRouter = require('./agents');
const allCoursesRouter = require('./allcourses');
const authRouter = require('./auth');
const complaintsRouter = require('./complaints');
const communicationsRouter = require('./communications');
const coursekewordsRouter = require('./coursekeywords');
const coursesRouter = require('./courses');
const documentationsRouter = require('./documentations');
const docsModiRouter = require('./documents_modification');
const expensesRouter = require('./expenses');
const editorsRouter = require('./editors');
const eventsRouter = require('./events');
const interviewsRouter = require('./interviews');
const notesRouter = require('./notes');
const portalsRouter = require('./portal_information');
const programRequirementsRouter = require('./program_requirements');
const programsRouter = require('./programs');
const permissionsRouter = require('./permissions');
const searchesRouter = require('./searches');
const studentsRouter = require('./students');
const studentsApplicationRouter = require('./student_applications');
const taigeraisRouter = require('./taigerais');
const teamsRouter = require('./teams');
const ticketsRouter = require('./tickets');
const uniassistRouter = require('./uniassist');
const usersRouter = require('./users');
const userlogsRouter = require('./userlogs');
const widgetsRouter = require('./widget');
const essayWriterRouter = require('./essay-writers');

const router = (app) => {
  const apiRouter = Router();
  apiRouter.use('/account', accountRouter);
  apiRouter.use('/student-applications', studentsApplicationRouter);
  apiRouter.use('/students', studentsRouter);
  apiRouter.use('/agents', agentsRouter);
  apiRouter.use('/all-courses', allCoursesRouter);
  apiRouter.use('/editors', editorsRouter);
  apiRouter.use('/essay-writers', essayWriterRouter);
  apiRouter.use('/admissions', admissionsRouter);
  apiRouter.use('/course-keywords', coursekewordsRouter);
  apiRouter.use('/courses', coursesRouter);
  apiRouter.use('/complaints', complaintsRouter);
  apiRouter.use('/communications', communicationsRouter);
  apiRouter.use('/docs', documentationsRouter);
  apiRouter.use('/document-threads', docsModiRouter);
  apiRouter.use('/expenses', expensesRouter);
  apiRouter.use('/events', eventsRouter);
  apiRouter.use('/interviews', interviewsRouter);
  apiRouter.use('/notes', notesRouter);
  apiRouter.use('/portal-informations', portalsRouter);
  apiRouter.use('/permissions', permissionsRouter);
  apiRouter.use('/program-requirements', programRequirementsRouter);
  apiRouter.use('/programs', programsRouter);
  apiRouter.use('/search', searchesRouter);
  apiRouter.use('/taigerai', taigeraisRouter);
  apiRouter.use('/teams', teamsRouter);
  apiRouter.use('/tickets', ticketsRouter);
  apiRouter.use('/uniassist', uniassistRouter);
  apiRouter.use('/users', usersRouter);
  apiRouter.use('/userlogs', userlogsRouter);
  apiRouter.use('/widgets', widgetsRouter);

  app.use('/api', apiRouter);
  app.use('/auth', authRouter);
};

module.exports = router;
