import xlsxwriter
from CourseSuggestionAlgorithms import *
from util import *
from keywords import *
from database.ElectricalEngineering.EE_Programs import program_sort_function, column_len_array
from cell_formatter import red_out_failed_subject, red_out_insufficient_credit
import pandas as pd
import sys
import os
env_file_path = os.path.realpath(__file__)
env_file_path = os.path.dirname(env_file_path)


def EE_sorter(program_idx, file_path, abbrev, studentId, student_name, analysis_language):

    basic_classification_en = {
        '微積分': [CALCULUS_KEY_WORDS_EN, CALCULUS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '數學': [ME_MATH_KEY_WORDS_EN, ME_MATH_ANTI_KEY_WORDS_EN],
        '物理': [GENERAL_PHYSICS_KEY_WORDS_EN, GENERAL_PHYSICS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '進階物理': [EE_ADVANCED_PHYSICS_KEY_WORDS_EN, EE_ADVANCED_PHYSICS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '物理實驗': [PHYSICS_EXP_KEY_WORDS_EN, PHYSICS_EXP_ANTI_KEY_WORDS_EN, ['一', '二']],
        '資訊': [EE_INTRO_COMPUTER_SCIENCE_KEY_WORDS_EN, EE_INTRO_COMPUTER_SCIENCE_ANTI_KEY_WORDS_EN],
        '程式': [PROGRAMMING_LANGUAGE_KEY_WORDS_EN, PROGRAMMING_LANGUAGE_ANTI_KEY_WORDS_EN],
        '軟體工程': [SOFTWARE_ENGINEERING_KEY_WORDS_EN, SOFTWARE_ENGINEERING_ANTI_KEY_WORDS_EN],
        '控制系統': [CONTROL_THEORY_KEY_WORDS_EN, CONTROL_THEORY_ANTI_KEY_WORDS_EN],
        '電子': [ELECTRONICS_KEY_WORDS_EN, ELECTRONICS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '電子實驗': [ELECTRONICS_EXPERIMENT_KEY_WORDS_EN, ELECTRONICS_EXPERIMENT_ANTI_KEY_WORDS_EN, ['一', '二']],
        '電路': [ELECTRO_CIRCUIT_KEY_WORDS_EN, ELECTRO_CIRCUIT_ANTI_KEY_WORDS_EN, ['一', '二']],
        '訊號系統': [SIGNAL_SYSTEM_KEY_WORDS_EN, SIGNAL_SYSTEM_ANTI_KEY_WORDS_EN],
        '電磁': [ELECTRO_MAGNET_KEY_WORDS_EN, ELECTRO_MAGNET_ANTI_KEY_WORDS_EN, ['一', '二']],
        '電力電子': [POWER_ELECTRONICS_KEY_WORDS_EN, POWER_ELECTRONICS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '通訊': [COMMUNICATION_ENGINEERING_KEY_WORDS_EN, COMMUNICATION_ENGINEERING_ANTI_KEY_WORDS_EN, ['一', '二']],
        '半導體': [SEMICONDUCTOR_KEY_WORDS_EN, SEMICONDUCTOR_ANTI_KEY_WORDS_EN],
        '電子材料': [ELECTRICAL_MATERIALS_KEY_WORDS_EN, ELECTRICAL_MATERIALS_ANTI_KEY_WORDS_EN],
        '進階電磁理論': [EE_HF_RF_THEO_INFO_KEY_WORDS_EN, EE_HF_RF_THEO_INFO_ANTI_KEY_WORDS_EN],
        '電機專業選修': [EE_ADVANCED_ELECTRO_KEY_WORDS_EN, EE_ADVANCED_ELECTRO_ANTI_KEY_WORDS_EN],
        '專業應用課程': [EE_APPLICATION_ORIENTED_KEY_WORDS_EN, EE_APPLICATION_ORIENTED_ANTI_KEY_WORDS_EN],
        '力學': [EE_MACHINE_RELATED_KEY_WORDS_EN, EE_MACHINE_RELATED_ANTI_KEY_WORDS_EN],
        '電路設計': [ELECTRO_CIRCUIT_DESIGN_KEY_WORDS_EN, ELECTRO_CIRCUIT_DESIGN_ANTI_KEY_WORDS_EN],
        '其他': [USELESS_COURSES_KEY_WORDS_EN, USELESS_COURSES_ANTI_KEY_WORDS_EN], }

    basic_classification_zh = {
        '微積分': [CALCULUS_KEY_WORDS, CALCULUS_ANTI_KEY_WORDS, ['一', '二']],
        '數學': [ME_MATH_KEY_WORDS, ME_MATH_ANTI_KEY_WORDS],
        '物理': [GENERAL_PHYSICS_KEY_WORDS, GENERAL_PHYSICS_ANTI_KEY_WORDS, ['一', '二']],
        '進階物理': [EE_ADVANCED_PHYSICS_KEY_WORDS, EE_ADVANCED_PHYSICS_ANTI_KEY_WORDS, ['一', '二']],
        '物理實驗': [PHYSICS_EXP_KEY_WORDS, PHYSICS_EXP_ANTI_KEY_WORDS, ['一', '二']],
        '資訊': [EE_INTRO_COMPUTER_SCIENCE_KEY_WORDS, EE_INTRO_COMPUTER_SCIENCE_ANTI_KEY_WORDS],
        '程式': [PROGRAMMING_LANGUAGE_KEY_WORDS, PROGRAMMING_LANGUAGE_ANTI_KEY_WORDS],
        '軟體工程': [SOFTWARE_ENGINEERING_KEY_WORDS, SOFTWARE_ENGINEERING_ANTI_KEY_WORDS],
        '控制系統': [CONTROL_THEORY_KEY_WORDS, CONTROL_THEORY_ANTI_KEY_WORDS],
        '電子': [ELECTRONICS_KEY_WORDS, ELECTRONICS_ANTI_KEY_WORDS, ['一', '二']],
        '電子實驗': [ELECTRONICS_EXPERIMENT_KEY_WORDS, ELECTRONICS_EXPERIMENT_ANTI_KEY_WORDS, ['一', '二']],
        '電路': [ELECTRO_CIRCUIT_KEY_WORDS, ELECTRO_CIRCUIT_ANTI_KEY_WORDS, ['一', '二']],
        '訊號系統': [SIGNAL_SYSTEM_KEY_WORDS, SIGNAL_SYSTEM_ANTI_KEY_WORDS],
        '電磁': [ELECTRO_MAGNET_KEY_WORDS, ELECTRO_MAGNET_ANTI_KEY_WORDS, ['一', '二']],
        '電力電子': [POWER_ELECTRONICS_KEY_WORDS, POWER_ELECTRONICS_ANTI_KEY_WORDS, ['一', '二']],
        '通訊': [COMMUNICATION_ENGINEERING_KEY_WORDS, COMMUNICATION_ENGINEERING_ANTI_KEY_WORDS, ['一', '二']],
        '半導體': [SEMICONDUCTOR_KEY_WORDS, SEMICONDUCTOR_ANTI_KEY_WORDS],
        '電子材料': [ELECTRICAL_MATERIALS_KEY_WORDS, ELECTRICAL_MATERIALS_ANTI_KEY_WORDS],
        '進階電磁理論': [EE_HF_RF_THEO_INFO_KEY_WORDS, EE_HF_RF_THEO_INFO_ANTI_KEY_WORDS],
        '電機專業選修': [EE_ADVANCED_ELECTRO_KEY_WORDS, EE_ADVANCED_ELECTRO_ANTI_KEY_WORDS],
        '專業應用課程': [EE_APPLICATION_ORIENTED_KEY_WORDS, EE_APPLICATION_ORIENTED_ANTI_KEY_WORDS],
        '力學': [EE_MACHINE_RELATED_KEY_WORDS, EE_MACHINE_RELATED_ANTI_KEY_WORDS],
        '電路設計': [ELECTRO_CIRCUIT_DESIGN_KEY_WORDS, ELECTRO_CIRCUIT_DESIGN_ANTI_KEY_WORDS],
        '其他': [USELESS_COURSES_KEY_WORDS, USELESS_COURSES_ANTI_KEY_WORDS], }

    Classifier(program_idx, file_path, abbrev, env_file_path,
               basic_classification_en, basic_classification_zh, column_len_array, program_sort_function, studentId, student_name, analysis_language)
