import xlsxwriter
from CourseSuggestionAlgorithms import *
from util import *
from keywords import *
from database.Biology.BIO_Programs import program_sort_function, column_len_array
from cell_formatter import red_out_failed_subject, red_out_insufficient_credit
import pandas as pd
import sys
import os
env_file_path = os.path.realpath(__file__)
env_file_path = os.path.dirname(env_file_path)


def FOR_sorter(program_idx, file_path, abbrev, studentId, student_name, analysis_language):

    basic_classification_en = {
        '微積分': [CALCULUS_KEY_WORDS_EN, CALCULUS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '線性代數': [MATH_LINEAR_ALGEBRA_KEY_WORDS_EN, MATH_LINEAR_ALGEBRA_ANTI_KEY_WORDS_EN],
        '離散': [MATH_DISCRETE_KEY_WORDS_EN, MATH_DISCRETE_ANTI_KEY_WORDS_EN],
        '數值分析': [MATH_NUM_METHOD_KEY_WORDS_EN, MATH_NUM_METHOD_ANTI_KEY_WORDS_EN],
        '機率與統計': [MATH_PROB_KEY_WORDS_EN, MATH_PROB_ANTI_KEY_WORDS_EN],
        '數學': [DSBI_MATH_KEY_WORDS_EN, DSBI_MATH_ANTI_KEY_WORDS_EN],
        '普通物理': [GENERAL_PHYSICS_KEY_WORDS_EN, GENERAL_PHYSICS_ANTI_KEY_WORDS_EN, ['一', '二']],
        '物理實驗': [PHYSICS_EXP_KEY_WORDS_EN, PHYSICS_EXP_ANTI_KEY_WORDS_EN, ['一', '二']],
        '力學': [MECHANIK_KEY_WORDS_EN, MECHANIK_ANTI_KEY_WORDS_EN, ['一', '二']],
        '進階物理': [EE_ADVANCED_PHYSICS_KEY_WORDS_EN, EE_ADVANCED_PHYSICS_ANTI_KEY_WORDS_EN],
        '分子物理': [ATOM_PHYSICS_KEY_WORDS_EN, ATOM_PHYSICS_ANTI_KEY_WORDS_EN],
        '量子物理': [QUANTUM_PHYSICS_KEY_WORDS_EN, QUANTUM_PHYSICS_ANTI_KEY_WORDS_EN],
        '凝態物理': [CONDENSED_MATTER_PHYSICS_KEY_WORDS_EN, CONDENSED_MATTER_PHYSICS_ANTI_KEY_WORDS_EN],
        '核物理': [NUCLEAR_PHYSICS_KEY_WORDS_EN, NUCLEAR_PHYSICS_ANTI_KEY_WORDS_EN],
        '天文物理': [ASTRO_PHYSICS_KEY_WORDS_EN, ASTRO_PHYSICS_ANTI_KEY_WORDS_EN],
        '普通化學': [GENERAL_CHEMISTRY_KEY_WORDS_EN, GENERAL_CHEMISTRY_ANTI_KEY_WORDS_EN],
        '有機化學': [ORGANIC_CHEMISTRY_KEY_WORDS_EN, ORGANIC_CHEMISTRY_ANTI_KEY_WORDS_EN],
        '進階化學': [BOE_ADVANCED_CHEMISTRY_KEY_WORDS_EN, BOE_ADVANCED_CHEMISTRY_ANTI_KEY_WORDS_EN],
        '無機化學': [INORGANIC_CHEMISTRY_KEY_WORDS_EN, INORGANIC_CHEMISTRY_ANTI_KEY_WORDS_EN],
        '生物化學': [BIO_CHEMISTRY_ONE_KEY_WORDS_EN, BIO_CHEMISTRY_ONE_ANTI_KEY_WORDS_EN],
        '物理化學': [PHYSICAL_CHEMISTRYY_KEY_WORDS_EN, PHYSICAL_CHEMISTRYY_ANTI_KEY_WORDS_EN],
        '電磁學': [ELECTRO_MAGNET_KEY_WORDS_EN, ELECTRO_MAGNET_ANTI_KEY_WORDS_EN],
        '熱力學': [THERMODYN_KEY_WORDS_EN, THERMODYN_ANTI_KEY_WORDS_EN],
        '論文': [BACHELOR_THESIS_KEY_WORDS_EN, BACHELOR_THESIS_ANTI_KEY_WORDS_EN],
        '其他': [USELESS_COURSES_KEY_WORDS_EN, USELESS_COURSES_ANTI_KEY_WORDS_EN], }

    basic_classification_zh = {
        '微積分': [CALCULUS_KEY_WORDS, CALCULUS_ANTI_KEY_WORDS, ['一', '二']],
        '線性代數': [MATH_LINEAR_ALGEBRA_KEY_WORDS, MATH_LINEAR_ALGEBRA_ANTI_KEY_WORDS],
        '離散': [MATH_DISCRETE_KEY_WORDS, MATH_DISCRETE_ANTI_KEY_WORDS],
        '數值分析': [MATH_NUM_METHOD_KEY_WORDS, MATH_NUM_METHOD_ANTI_KEY_WORDS],
        '機率與統計': [MATH_PROB_KEY_WORDS, MATH_PROB_ANTI_KEY_WORDS],
        '數學': [DSBI_MATH_KEY_WORDS, DSBI_MATH_ANTI_KEY_WORDS],
        '普通物理': [GENERAL_PHYSICS_KEY_WORDS, GENERAL_PHYSICS_ANTI_KEY_WORDS, ['一', '二']],
        '物理實驗': [PHYSICS_EXP_KEY_WORDS, PHYSICS_EXP_ANTI_KEY_WORDS, ['一', '二']],
        '力學': [MECHANIK_KEY_WORDS, MECHANIK_ANTI_KEY_WORDS, ['一', '二']],
        '進階物理': [EE_ADVANCED_PHYSICS_KEY_WORDS, EE_ADVANCED_PHYSICS_ANTI_KEY_WORDS],
        '分子物理': [ATOM_PHYSICS_ANTI_KEY_WORDS, ATOM_PHYSICS_ANTI_KEY_WORDS],
        '量子物理': [QUANTUM_PHYSICS_KEY_WORDS, QUANTUM_PHYSICS_ANTI_KEY_WORDS],
        '凝態物理': [CONDENSED_MATTER_PHYSICS_KEY_WORDS, CONDENSED_MATTER_PHYSICS_ANTI_KEY_WORDS],
        '核物理': [NUCLEAR_PHYSICS_KEY_WORDS, NUCLEAR_PHYSICS_ANTI_KEY_WORDS],
        '天文物理': [ASTRO_PHYSICS_KEY_WORDS, ASTRO_PHYSICS_ANTI_KEY_WORDS],
        '普通化學': [GENERAL_CHEMISTRY_KEY_WORDS, GENERAL_CHEMISTRY_ANTI_KEY_WORDS],
        '有機化學': [ORGANIC_CHEMISTRY_KEY_WORDS, ORGANIC_CHEMISTRY_ANTI_KEY_WORDS],
        '進階化學': [BOE_ADVANCED_CHEMISTRY_KEY_WORDS, BOE_ADVANCED_CHEMISTRY_ANTI_KEY_WORDS],
        '無機化學': [INORGANIC_CHEMISTRY_KEY_WORDS, INORGANIC_CHEMISTRY_ANTI_KEY_WORDS],
        '生物化學': [BIO_CHEMISTRY_ONE_KEY_WORDS, BIO_CHEMISTRY_ONE_ANTI_KEY_WORDS],
        '物理化學': [PHYSICAL_CHEMISTRYY_KEY_WORDS, PHYSICAL_CHEMISTRYY_ANTI_KEY_WORDS],
        '電磁學': [ELECTRO_MAGNET_KEY_WORDS, ELECTRO_MAGNET_ANTI_KEY_WORDS],
        '熱力學': [THERMODYN_KEY_WORDS, THERMODYN_ANTI_KEY_WORDS],
        '論文': [BACHELOR_THESIS_KEY_WORDS, BACHELOR_THESIS_ANTI_KEY_WORDS],
        '其他': [USELESS_COURSES_KEY_WORDS, USELESS_COURSES_ANTI_KEY_WORDS], }

    Classifier(program_idx, file_path, abbrev, env_file_path,
               basic_classification_en, basic_classification_zh, column_len_array, program_sort_function, studentId, student_name, analysis_language)
